#!/bin/bash

OLD_DIR=$(pwd)
TEST_DONE=0

clean_up () {
    cd $OLD_DIR
    unset OLD_DIR
}


clean_up_and_exit () {
    echo "Error at: $1 with exit code $2"
    clean_up;
    exit $2;
}


install_deployer () {
    dpkg-deb --build $OLD_DIR/deployer \
      && sudo dpkg --install $OLD_DIR/deployer.deb \
      || exit 1;
}


echo_test_done () {
    echo "Done";
    TEST_DONE=$(($TEST_DONE + 1));
}

run_test () {
    printf "Testing $1: "
    cd /tmp/test-deployer
    $OLD_DIR/tests/$1 > /dev/null
    test_exit_code=$?
    [ "$test_exit_code" -ne "0" ] && clean_up_and_exit $1 $test_exit_code \
      || echo_test_done
}


rm -rf /tmp/test-deployer
mkdir  /tmp/test-deployer
cd     /tmp/test-deployer

install_deployer > /dev/null

run_test "01_test_empty_dir"
run_test "05_initiate_project" <<< "my_stdin"
run_test "08_test_multiple_dir"

echo "Done. Ran $TEST_DONE tests."
