#!/bin/bash


echo_test_error_104 () {
    echo "deployer not supposed to find any file";
    exit 204;
}


dir_not_found () {
    deployer
    [ "$?" -ne "104" ] && echo_test_error_104;
}


dir_not_found;
exit 0;
