#!/bin/bash


echo_test_error_105 () {
    echo "deployer supposed to find multiple files";
    exit 205;
}


multi_dir_found () {
    deployer
    [ "$?" -ne "105" ] && echo_test_error_105
}


multi_dir_found
exit 0;
