#!/bin/bash


library_path="";
library_name="${1,,}";
program_name="${2,,}";


clean_up () {
    unset DEPLOYER_BASE_DIR;
}


print_error_and_exit () {
  cat /usr/lib/deployer/errors/${1}.txt;
  exit ${1};
}


print_help_and_exit () {
    cat /usr/lib/deployer/${library_name}/help.txt 2> /dev/null \
      || cat /usr/lib/deployer/help.txt;
    clean_up;
    exit 1;
}


set_library_path () {
    # if program_name equal to help
    [ -d /usr/lib/deployer/${library_name} ] \
      && [ "$program_name" = "help" ] \
      && print_help_and_exit;

    # if program_name existe
    [  !   -d /usr/lib/deployer/${library_name}/${program_name} ] \
      && [ -x /usr/lib/deployer/${library_name}/${program_name} ] \
      && library_path="/usr/lib/deployer/${library_name}/${program_name}" \
      && return 0;
    
    # if main program existe
    [ -x /usr/lib/deployer/${library_name}/main ] \
      && library_path="/usr/lib/deployer/${library_name}/main" \
      && return 0;

    print_help_and_exit;
}


[ -n "$library_name" ] \
  && set_library_path \
  || print_help_and_exit;

shift;

$library_path $@ \
  || print_error_and_exit $? ;
clean_up;
