#!/bin/bash


kubectl_version="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
kubectl_binary_link="https://storage.googleapis.com/kubernetes-release/release/${kubectl_version}/bin/linux/amd64/kubectl"


cd /tmp/ \
&& sudo echo 'update kubectl to ' ${kubectl_version} \
&& sudo curl -fLO ${kubectl_binary_link} \
&& sudo chmod +x ./kubectl \
&& sudo mv ./kubectl /usr/local/bin/kubectl \
&& echo 'done updating kubectl'
