#!/bin/bash


print_help_and_exit () {
  cat /usr/lib/install/help.txt;
  exit 1; 
}


app_name="${1,,}"

shift;


[ -n "${app_name}" ] \
  && [ -x /usr/lib/deployer/install/${app_name} ] \
  || print_help_and_exit

/usr/lib/deployer/install/${app_name} $@;
