#!/bin/bash

minikube_binary_link="https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"

cd /tmp/ \
&& sudo echo 'update minikube to latest' \
&& curl -LO ${minikube_binary_link} \
&& chmod +x minikube-linux-amd64 \
&& sudo mv minikube-linux-amd64 /usr/local/bin/minikube \
&& echo 'done updating minikube'
