#!/bin/bash


echo_error_104 () {
    echo "Could not find the values/main.ini file!"
    echo "Kindly run: deployer init"
    exit 104;
}


echo_error_105 () {
    echo "There are multiple values/main.ini files!"
    echo "Kindly relocate to one of them!"
    exit 105;
}


all_base_dir="$(find $(pwd) -type f -wholename '*/values/main.ini')"
count_base_dir="$(find $(pwd) -type f -wholename '*/values/main.ini' | wc -l)"


[ "$count_base_dir" -gt "1" ] && echo_error_105
[ "$count_base_dir" -ne "1" ] && echo_error_104


export DEPLOYER_BASE_DIR="$(echo $all_base_dir | sed -e 's/values\/main\.ini//')"
