#!/bin/bash


all_base_dir="$(find $(pwd) -type f -wholename '*/values/main.ini')"
count_base_dir="$(find $(pwd) -type f -wholename '*/values/main.ini' | wc -l)"


[ "$count_base_dir" -gt "1" ] && exit 105;
[ "$count_base_dir" -ne "1" ] && exit 104;


export DEPLOYER_BASE_DIR="$(echo $all_base_dir | sed -e 's/values\/main\.ini//')"
