#!/bin/bash


[ -n "$DJANGO_PATH" ] \
  || source ${LIBRARY_BASE}/django/path


echo ok >>>>>>>>>>>> $DJANGO_PATH


# check if django installed in .venv or install it 


















# pip3 install -r ./requirements.txt \
#   && python3 manage.py makemigrations \
#   && python3 manage.py migrate \
#   && python3 manage.py collectstatic --noinput
