#!/bin/bash

set -eu -o pipefail


source ${LIBRARY_BASE}/django/venv


pip3 install -r ./requirements.txt \
  && python3 manage.py makemigrations \
  && python3 manage.py migrate \
  || exit 108


python3 manage.py collectstatic --noinput \
  || exit 109


python3 manage.py runserver

echo ""
echo "Stopping django"
