#!/bin/bash


DEPLOYER_INIT_DIR=$(pwd)


read_project_name () {
    printf "Kindly enter your project name: "; 
    read PROJECT_NAME;
}


[ -n "${1}" ] \
  && PROJECT_NAME="${1}" \
  || read_project_name


[ -d "$PROJECT_NAME" ] || mkdir $PROJECT_NAME
cd $PROJECT_NAME

[ -d "values" ] || mkdir values


if [ ! -f values/main.ini ]; then 
  cat <<EOF > values/main.ini
[project]
name=$PROJECT_NAME
EOF
fi


/usr/lib/deployer/django/initiate $PROJECT_NAME
