#!/bin/bash


set -eu -o pipefail

export ARGS=("${@,,}")


add_extra_settings () {
  cat ${LIBRARY_BASE}/new/templates/django/settings.py >> \
    ./${PROJECT_NAME}/django/${PROJECT_NAME}/settings.py
}


clean_up_exit_107 () {
    rm -rf ./${PROJECT_NAME}/django
    exit 107
}


source ${LIBRARY_BASE}/new/get_project_name $@

mkdir ./${PROJECT_NAME}/django

python3 -m venv ./${PROJECT_NAME}/django/.venv

source ./${PROJECT_NAME}/django/.venv/bin/activate

pip3 install Django \
  && django-admin startproject ${PROJECT_NAME} ./${PROJECT_NAME}/django \
  && pip3 freeze > ./${PROJECT_NAME}/django/requirements.txt \
  && add_extra_settings \
  || clean_up_exit_107

export PROJECT_NAME



[ "skip" = "${ARGS[1]:-}" ] \
  || source ${LIBRARY_BASE}/django/main 
