#!/bin/bash


set -eu -o pipefail

export ARGS=("${@,,}")


read_project_name () {
  printf "Kindly enter your project name: "; 
  read PROJECT_NAME;
}


[ -n "${ARGS[1]:-}" ] \
  && [ ! "skip" = "${ARGS[1]}" ] \
  && PROJECT_NAME="${ARGS[1]}" \
  || read_project_name \


[ -n "$PROJECT_NAME" ] \
  || exit 106


[ ! -d "$PROJECT_NAME" ] \
  || exit 105 \
  && mkdir ./${PROJECT_NAME} \
  || exit 110 \
  && cp ${LIBRARY_BASE}/new/templates/.gitignore ./${PROJECT_NAME}


export PROJECT_NAME
